#!/usr/bin/make -f

# directories

TMP_DIR = $(MODULES_BASE_DIR)/tmp/

# target: dependencies
#	action

all:
	$(Q)make -C $(TMP_DIR)

clean:
	$(Q)make clean -C $(TMP_DIR)

################################################################################
######## End of file ###########################################################
################################################################################
